module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0b1326",
        "on-secondary-fixed-variant": "#92002a",
        "surface-container-lowest": "#060e20",
        "secondary-fixed-dim": "#ffb2b7",
        "secondary": "#ffb2b7",
        "surface-container-high": "#222a3d",
        "on-tertiary-container": "#b67300",
        "inverse-surface": "#dae2fd",
        "on-primary": "#003824",
        "on-tertiary": "#472a00",
        "surface-container-highest": "#2d3449",
        "inverse-primary": "#006c49",
        "surface-bright": "#31394d",
        "on-secondary-container": "#ffc2c4",
        "primary-fixed-dim": "#4edea3",
        "outline-variant": "#44474d",
        "surface-container-low": "#131b2e",
        "primary": "#4edea3",
        "outline": "#8f9097",
        "on-primary-fixed": "#002113",
        "background": "#0b1326",
        "secondary-container": "#b50036",
        "primary-container": "#001e11",
        "primary-fixed": "#6ffbbe",
        "on-surface-variant": "#c5c6cd",
        "on-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "on-secondary": "#67001b",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-fixed": "#40000d",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "on-primary-container": "#009466",
        "on-background": "#dae2fd",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-tint": "#4edea3",
        "surface-container": "#171f33",
        "tertiary": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#271500",
        "secondary-fixed": "#ffdadb",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#005236"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"]
      },
      boxShadow: {
        "sidebar": "20px 0 30px rgba(45,52,73,0.1)",
      },
    },
  },
  plugins: [],
}
