"""SQLAlchemy ORM models for Stock Market Intelligence."""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker

logger = logging.getLogger(__name__)

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://localhost/stock_intelligence")


def _make_engine(url: str):
    """Create a SQLAlchemy engine with appropriate settings for the dialect."""
    if url.startswith("sqlite"):
        return create_engine(url, connect_args={"check_same_thread": False})
    connect_args: dict = {}
    if "postgresql" in url:
        connect_args = {"connect_timeout": 10}
    return create_engine(
        url,
        pool_pre_ping=True,
        pool_size=5,
        max_overflow=10,
        connect_args=connect_args,
    )


engine = _make_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)


def _utcnow() -> datetime:
    """Return a timezone-aware UTC datetime."""
    return datetime.now(tz=timezone.utc)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


class Article(Base):
    """News article scraped from financial sources."""

    __tablename__ = "articles"
    __table_args__ = (Index("ix_articles_ticker_date", "ticker", "published_date"),)

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), index=True)
    title = Column(String(500))
    content = Column(Text)
    source = Column(String(100))
    url = Column(String(500), unique=True)
    published_date = Column(DateTime)
    created_at = Column(DateTime, default=_utcnow)

    def __repr__(self) -> str:
        return f"<Article(id={self.id}, ticker={self.ticker!r}, source={self.source!r})>"


class Signal(Base):
    """Trading signal generated by the signal engine."""

    __tablename__ = "signals"
    __table_args__ = (Index("ix_signals_ticker_created", "ticker", "created_at"),)

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), index=True)
    signal_type = Column(String(20))
    combined_score = Column(Float)
    technical_score = Column(Float)
    sentiment_score = Column(Float)
    confidence = Column(Float)
    latest_price = Column(Float)
    price_change_percent = Column(Float)
    created_at = Column(DateTime, default=_utcnow, index=True)

    def __repr__(self) -> str:
        return f"<Signal(id={self.id}, ticker={self.ticker!r}, type={self.signal_type!r})>"


class Sentiment(Base):
    """Sentiment analysis result for a ticker."""

    __tablename__ = "sentiments"
    __table_args__ = (Index("ix_sentiments_ticker_created", "ticker", "created_at"),)

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), index=True)
    sentiment = Column(String(20))
    confidence = Column(Float)
    positive_score = Column(Float)
    negative_score = Column(Float)
    neutral_score = Column(Float)
    created_at = Column(DateTime, default=_utcnow)

    def __repr__(self) -> str:
        return f"<Sentiment(id={self.id}, ticker={self.ticker!r}, sentiment={self.sentiment!r})>"


class Portfolio(Base):
    """User-defined portfolio of tickers."""

    __tablename__ = "portfolios"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100))
    description = Column(Text)
    tickers = Column(String(500))
    created_at = Column(DateTime, default=_utcnow)

    def __repr__(self) -> str:
        return f"<Portfolio(id={self.id}, name={self.name!r})>"


class BacktestResult(Base):
    """Result of a backtesting run for a strategy."""

    __tablename__ = "backtest_results"
    __table_args__ = (Index("ix_backtest_ticker_strategy", "ticker", "strategy"),)

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), index=True)
    strategy = Column(String(100))
    total_return = Column(Float)
    win_rate = Column(Float)
    sharpe_ratio = Column(Float)
    trades_count = Column(Integer)
    created_at = Column(DateTime, default=_utcnow)

    def __repr__(self) -> str:
        return f"<BacktestResult(id={self.id}, ticker={self.ticker!r}, strategy={self.strategy!r})>"


def init_db() -> None:
    """Create all database tables."""
    Base.metadata.create_all(bind=engine)
    logger.info("Database initialised successfully")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    init_db()
